const GAME_WIDTH = 1280;
const GAME_HEIGHT = 720;

const MAX_PARTICLES = 450;
const MAX_FLOATING_TEXTS = 90;
const MAX_ACTIVE_ENEMIES = 170;
const MAX_ACTIVE_PROJECTILES = 260;

const HORDE_PRESSURE_RADIUS = 155;
const HORDE_PRESSURE_START = 12;
const HORDE_PRESSURE_TICK = 0.22;
const HORDE_PRESSURE_BASE_DAMAGE = 4;
const HORDE_PRESSURE_DAMAGE_PER_EXTRA_ENEMY = 1.15;
const HORDE_PRESSURE_HEAL_LOCK = 0.45;

const ENEMY_GRID_SIZE = 140;

const ARCANE_CLONE_DURATION = 18;
const ARCANE_CLONE_OFFSET = 58;
const ARCANE_CLONE_DAMAGE_RATIO = 0.65;

const BEST_SCORE_STORAGE_KEYS = ["runeSurvivorBestScore", "runeSurvivor.bestScore", "RuneSurvivor_BEST_SCORE"];
const BEST_SCORE_STATS_KEY = "runeSurvivor.stats";
const CURRENT_RUN_STORAGE_KEY = "runeSurvivor.currentRun";

const LIFE_STEAL_MAX_HEAL_PER_SECOND_RATIO = 0.10;
const LIFE_STEAL_MIN_HEAL_PER_SECOND = 8;
const HIT_HEAL_LOCK_DURATION = 0.22;
const SPIKE_HEAL_LOCK_DURATION = 1.15;

const SKILL_TIER_COST_MULTIPLIER = 2.8;
const SKILL_TIER_EFFECT_BONUS = 0.25;
const MAX_VISIBLE_SKILL_TIER = 99;