const GAME_WIDTH = 1280;
const GAME_HEIGHT = 720;

// DEBUG
const DEBUG_BOSS_TEST_ENABLED = false; // set to true to enable boss test buttons in the main menu

const MAX_PARTICLES = 450;
const MAX_FLOATING_TEXTS = 90;
const MAX_ACTIVE_ENEMIES = 170;
const MAX_ACTIVE_PROJECTILES = 260;
const ENEMY_CAP_BEFORE_BOSS_1 = 120;
const ENEMY_CAP_AFTER_BOSS_1 = 40;
const ENEMY_CAP_AFTER_BOSS_2 = 60;
const ENEMY_CAP_AFTER_BOSS_3 = 100;

const SPAWN_INTERVAL_MULTIPLIER_AFTER_BOSS_1 = 1.55;
const SPAWN_INTERVAL_MULTIPLIER_AFTER_BOSS_2 = 1.32;
const SPAWN_INTERVAL_MULTIPLIER_AFTER_BOSS_3 = 1.15;

const HORDE_PRESSURE_RADIUS = 155;
const HORDE_PRESSURE_START = 12;
const HORDE_PRESSURE_TICK = 0.22;
const HORDE_PRESSURE_BASE_DAMAGE = 4;
const HORDE_PRESSURE_DAMAGE_PER_EXTRA_ENEMY = 1.15;
const HORDE_PRESSURE_HEAL_LOCK = 0.45;

const ENEMY_GRID_SIZE = 140;

const ARCANE_CLONE_DURATION = 18;
const ARCANE_CLONE_OFFSET = 58;
const ARCANE_CLONE_DAMAGE_RATIO = 0.65;

const BEST_SCORE_STORAGE_KEYS = ["runeSurvivorBestScore", "runeSurvivor.bestScore", "RuneSurvivor_BEST_SCORE"];
const BEST_SCORE_STATS_KEY = "runeSurvivor.stats";
const CURRENT_RUN_STORAGE_KEY = "runeSurvivor.currentRun";

const LIFE_STEAL_MAX_HEAL_PER_SECOND_RATIO = 0.10;
const LIFE_STEAL_MIN_HEAL_PER_SECOND = 8;
const HIT_HEAL_LOCK_DURATION = 0.22;
const SPIKE_HEAL_LOCK_DURATION = 1.15;

const SKILL_TIER_COST_MULTIPLIER = 2.8;
const SKILL_TIER_EFFECT_BONUS = 0.25;
const MAX_VISIBLE_SKILL_TIER = 0; // nombre de palier/tier max de l'arbre de compétence

// orange enemy
const COWARD_SHOOTER_SPAWN_CHANCE = 0.18;
const COWARD_SHOOTER_SPEED_MULTIPLIER = 1.45;

const COWARD_SHOOTER_PREFERRED_DISTANCE = 360;
const COWARD_SHOOTER_TOO_CLOSE_DISTANCE = 285;
const COWARD_SHOOTER_LEASH_DISTANCE = 560;

const COWARD_SHOOTER_FIRE_COOLDOWN_MIN = 1.35;
const COWARD_SHOOTER_FIRE_COOLDOWN_MAX = 1.85;
const COWARD_SHOOTER_PROJECTILE_SPEED = 330;
const COWARD_SHOOTER_PROJECTILE_RADIUS = 7;
const COWARD_SHOOTER_PROJECTILE_LIFETIME = 4.2;
const COWARD_SHOOTER_PROJECTILE_DAMAGE = 15;

const HORDE_BOMB_SPAWN_INTERVAL = 12;
const HORDE_BOMB_MIN_ENEMIES_TO_SPAWN = 30;

// grey enemy
const HORDE_BOMB_RADIUS = 30;
const HORDE_BOMB_SPEED = 400;
const HORDE_BOMB_HP = 999;
const HORDE_BOMB_EXPLOSION_RADIUS = 200;
const HORDE_BOMB_PLAYER_DAMAGE_RATIO = 0.20;
const HORDE_BOMB_KNOCKBACK_FORCE = 480;
const HORDE_BOMB_MAX_LIFE = 8;

const HORDE_BOMB_TARGET_SEARCH_RADIUS = 230;
const HORDE_BOMB_DETONATE_DISTANCE = 42;

const SUBMERGED_DAMAGE_MULTIPLIER = 3;
const SUBMERGED_DAMAGE_MIN_ENEMIES = HORDE_PRESSURE_START;
const SUBMERGED_DAMAGE_RADIUS = HORDE_PRESSURE_RADIUS;

// Trousse de soins
const HEAL_KIT_SPAWN_MIN = 18;
const HEAL_KIT_SPAWN_MAX = 28;
const HEAL_KIT_RADIUS = 17;
const HEAL_KIT_LIFE = 20;

const HEAL_KIT_HEAL_RATIO = 0.25;
const HEAL_KIT_MIN_HEAL = 25;
const HEAL_KIT_SPAWN_PLAYER_MIN_MISSING_HP_RATIO = 0.15;

// Rune légendaire
const LEGENDARY_UPGRADE_INTERVAL = 5; // tout les X niveaux, le joueur obtient une rune légendaire

// Rune légendaire : Orbe gardien
const GUARDIAN_ORB_ORBIT_RADIUS = 78;
const GUARDIAN_ORB_RADIUS = 12;
const GUARDIAN_ORB_SPEED = 4.4;
const GUARDIAN_ORB_DAMAGE_RATIO = 0.75;
const GUARDIAN_ORB_HIT_COOLDOWN = 0.42;
// Upgrades de l'orbe gardien
const GUARDIAN_ORB_DAMAGE_UPGRADE_BONUS = 0.25;
const GUARDIAN_ORB_SPEED_UPGRADE_BONUS = 0.18;
const GUARDIAN_ORB_DAMAGE_UPGRADE_MAX_LEVEL = 6;
const GUARDIAN_ORB_SPEED_UPGRADE_MAX_LEVEL = 6;
const GUARDIAN_ORB_MAX_COUNT = 4;

// Rune légendaire : Pluie astrale
const ASTRAL_RAIN_INTERVAL = 18;
const ASTRAL_RAIN_STRIKE_COUNT = 7;
const ASTRAL_RAIN_WARNING_DURATION = 0.75;
const ASTRAL_RAIN_ACTIVE_DURATION = 0.22;
const ASTRAL_RAIN_RADIUS = 58;
const ASTRAL_RAIN_DAMAGE_RATIO = 1.65;
// Upgrades de la Pluie astrale
const ASTRAL_RAIN_DAMAGE_UPGRADE_BONUS = 0.25;
const ASTRAL_RAIN_COOLDOWN_UPGRADE_REDUCTION = 2;
const ASTRAL_RAIN_MIN_INTERVAL = 8;
const ASTRAL_RAIN_STRIKE_UPGRADE_BONUS = 1;
const ASTRAL_RAIN_DAMAGE_UPGRADE_MAX_LEVEL = 6;
const ASTRAL_RAIN_COOLDOWN_UPGRADE_MAX_LEVEL = 5;
const ASTRAL_RAIN_STRIKE_UPGRADE_MAX_LEVEL = 5;

// Rune légendaire : Triple écho
const TRIPLE_ECHO_DURATION = 12;
const TRIPLE_ECHO_OFFSET = 76;
const TRIPLE_ECHO_DAMAGE_RATIO = 0.55;